version: "3.3"

services:

  app:
    build: ./app
    volumes:
      - ./app/app:/app
    stdin_open: true

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
